[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
dependencies = [
    'pyserial',
    'crccheck',
    'stm32loader',
    'requests',
    'flask',
    'numpy'
]
build-backend = "setuptools.build_meta"

